name: Deploy 
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          USERNAME: ${{ secrets.USER_NAME }}
          HOST: ${{ secrets.HOST }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
            cd discord_bot_v14
            git pull
            npm i
            pm2 stop chatbot
            pm2 start src/app.js --name chatbot
